export const mockAds = [
  {
    title: "شقة فاخرة للبيع في مدينة نصر",
    city: "القاهرة",
    area: "مدينة نصر",
    rooms: 3,
    space: 150,
    propertyType: "شقة",
    type: "تمليك",
    address: "شارع عباس العقاد، مدينة نصر، القاهرة",
    description:
      "شقة فاخرة للبيع في موقع مميز بمدينة نصر بالقرب من الخدمات والمواصلات. تشطيب سوبر لوكس.",
    price: 1500000,
    whatsappNumber: "01012345678",
    images: [
      "https://picsum.photos/600/400?random=1",
      "https://picsum.photos/600/400?random=2",
    ],
  },
  {
    title: "فيلا للإيجار في الشيخ زايد",
    city: "الجيزة",
    area: "الشيخ زايد",
    rooms: 5,
    space: 400,
    propertyType: "فيلا",
    type: "ايجار",
    address: "كمبوند بيفرلي هيلز، الشيخ زايد، الجيزة",
    description:
      "فيلا راقية للإيجار بحديقة خاصة وتشطيب فاخر. موقع هادئ ومناسب للعائلات.",
    price: 25000,
    whatsappNumber: "01198765432",
    images: [
      "https://picsum.photos/600/400?random=3",
      "https://picsum.photos/600/400?random=4",
    ],
  },
  {
    title: "شقة للبيع في المعادي",
    city: "القاهرة",
    area: "المعادي",
    rooms: 2,
    space: 120,
    propertyType: "شقة",
    type: "تمليك",
    address: "شارع النيل، المعادي، القاهرة",
    description:
      "شقة رائعة للبيع بالمعادي مع إطلالة جميلة على النيل. مناسبة للسكن أو الاستثمار.",
    price: 1800000,
    whatsappNumber: "01234567890",
    images: [
      "https://picsum.photos/600/400?random=5",
      "https://picsum.photos/600/400?random=6",
    ],
  },
  {
    title: "محل تجاري للإيجار في وسط البلد",
    city: "القاهرة",
    area: "وسط البلد",
    rooms: 1,
    space: 80,
    propertyType: "محل تجاري",
    type: "ايجار",
    address: "شارع طلعت حرب، وسط البلد، القاهرة",
    description:
      "محل تجاري للإيجار بمساحة مناسبة في قلب القاهرة وسط حركة نشطة وأسواق شعبية.",
    price: 10000,
    whatsappNumber: "01511223344",
    images: [
      "https://picsum.photos/600/400?random=7",
      "https://picsum.photos/600/400?random=8",
    ],
  },
  {
    title: "شقة للإيجار في الإسكندرية",
    city: "الإسكندرية",
    area: "سيدي بشر",
    rooms: 3,
    space: 160,
    propertyType: "شقة",
    type: "ايجار",
    address: "شارع البحر، سيدي بشر، الإسكندرية",
    description:
      "شقة مطلة على البحر للإيجار في سيدي بشر. قريبة من الكورنيش والخدمات العامة.",
    price: 7000,
    whatsappNumber: "01099887766",
    images: [
      "https://picsum.photos/600/400?random=9",
      "https://picsum.photos/600/400?random=10",
    ],
  },
];
